title: Advik Sinha
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Customizations
description: > #
  I'm a freshman at Vista Del Lago with a passion for business and finance. 
  <br><br>
  Methods to Contact Me:
  <br><br>
  <a href="https://www.linkedin.com/in/advik-sinha-16563a304/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/advikksinha/">View My Github Profile</a>
  <br><br>
  <span style="cursor:pointer; color: grey; text-decoration: underline;" onclick="showInfo('email')">My Email Address: advik.sinha2011@gmail.com</span>
